version: "3.5"

services:
  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - 8080:80
    networks:
      - spiritium-net

  backend:
    image: backend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - spiritium-net

  database:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - mongodata:/data/db
    networks:
      - spiritium-net
    command: ["--auth"]

networks:
  spiritium-net:
    name: spiritium-net
    driver: bridge

volumes:
  mongodata:
    driver: local